name: my_flutter_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43

version: 1.0.0+1

environment:
  sdk: ^3.5.0

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  geolocator: ^10.1.0
  http: ^1.2.0

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_generative_ai: ^0.2.0
  flutter_dotenv: ^5.0.2
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.2
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2
  flutter_pdfview: ^1.3.4
  record: ^5.0.0
  google_maps_flutter: ^2.5.3
  google_places_flutter: ^2.0.6
  image_picker: ^1.0.7
  image_picker_windows: ^0.2.1
  file_selector_windows: ^0.9.3
  file_picker: ^6.1.1
  twilio_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


 
  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/docs/
     - assets/docs/anony_doc.pdf
     - .env
     - assets/dialog.txt
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


